## Import necessary libs

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Load and get info on dataset

In [3]:
data=pd.read_csv("../WELFake_Dataset.csv")

In [4]:
data.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [5]:
data.set_index(data.columns[0], inplace=True)

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   71576 non-null  str
 1   text    72095 non-null  str
 2   label   72134 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.7 MB

In [7]:
data.isnull().sum()

title    558
text      39
label      0
dtype: int64

In [8]:
data['label'].value_counts()

label
1    37106
0    35028
Name: count, dtype: int64

1=ham
0=spam

In [9]:
data = data.dropna()
data

,title,text,label
Unnamed: 0,,,
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1
...,...,...,...
72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [10]:
data.info()

<class 'pandas.DataFrame'>
Index: 71537 entries, 0 to 72133
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   71537 non-null  str
 1   text    71537 non-null  str
 2   label   71537 non-null  int64
dtypes: int64(1), str(2)
memory usage: 2.2 MB

## Remove HTML tags and URLs

In [11]:
import re
def remove_tags(text):
    pattern = re.compile(r'<.*?>')
    return pattern.sub(r'', text)
def remove_links(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [12]:
data['title'] = data['title'].apply(remove_tags)
data['text'] = data['text'].apply(remove_tags)
data['title'] = data['title'].apply(remove_links)
data['text'] = data['text'].apply(remove_links)
data.head()

,title,text,label
Unnamed: 0,,,
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1

## Convert dataset into lowercase

In [13]:
data['title'] = data['title'].str.lower()
data['text'] = data['text'].str.lower()
data.head()

,title,text,label
Unnamed: 0,,,
0,law enforcement on high alert following threat...,no comment is expected from barack obama membe...,1
2,unbelievable! obama’s attorney general says mo...,"now, most of the demonstrators gathered last ...",1
3,"bobby jindal, raised hindu, uses story of chri...",a dozen politically active pastors came here f...,0
4,satan 2: russia unvelis an image of its terrif...,"the rs-28 sarmat missile, dubbed satan 2, will...",1
5,about time! christian group sues amazon and sp...,all we can say on this one is it s about time ...,1

## Remove punctuation marks

In [14]:
import string
pm = string.punctuation
def remove_punctuation(text):
    pattern = re.compile(r'[^\w\s]')
    return pattern.sub(r' ', text)

In [15]:
data['title'] = data['title'].apply(remove_punctuation)
data['text'] = data['text'].apply(remove_punctuation)

In [16]:
data.head()

,title,text,label
Unnamed: 0,,,
0,law enforcement on high alert following threat...,no comment is expected from barack obama membe...,1
2,unbelievable obama s attorney general says mo...,now most of the demonstrators gathered last ...,1
3,bobby jindal raised hindu uses story of chri...,a dozen politically active pastors came here f...,0
4,satan 2 russia unvelis an image of its terrif...,the rs 28 sarmat missile dubbed satan 2 will...,1
5,about time christian group sues amazon and sp...,all we can say on this one is it s about time ...,1

## Tokenize the dataset

In [17]:
from nltk.tokenize import word_tokenize
data['title_tokens'] = data['title'].apply(lambda x: word_tokenize(str(x)))
data['text_tokens'] = data['text'].apply(lambda x: word_tokenize(str(x)))
data.head()

,title,text,label,title_tokens,text_tokens
Unnamed: 0,,,,,
0,law enforcement on high alert following threat...,no comment is expected from barack obama membe...,1,"[law, enforcement, on, high, alert, following,...","[no, comment, is, expected, from, barack, obam..."
2,unbelievable obama s attorney general says mo...,now most of the demonstrators gathered last ...,1,"[unbelievable, obama, s, attorney, general, sa...","[now, most, of, the, demonstrators, gathered, ..."
3,bobby jindal raised hindu uses story of chri...,a dozen politically active pastors came here f...,0,"[bobby, jindal, raised, hindu, uses, story, of...","[a, dozen, politically, active, pastors, came,..."
4,satan 2 russia unvelis an image of its terrif...,the rs 28 sarmat missile dubbed satan 2 will...,1,"[satan, 2, russia, unvelis, an, image, of, its...","[the, rs, 28, sarmat, missile, dubbed, satan, ..."
5,about time christian group sues amazon and sp...,all we can say on this one is it s about time ...,1,"[about, time, christian, group, sues, amazon, ...","[all, we, can, say, on, this, one, is, it, s, ..."

## Remove stop words

In [18]:
from nltk.corpus import stopwords
sw = stopwords.words('english')
sw

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [19]:
def remove_stopwords(text):
    new_text = []
    for word in text:
        if word in sw:
            new_text.append('')
        else:
            new_text.append(word)
    return " ".join(new_text)

In [20]:
data['title_tokens'] = data['title_tokens'].apply(remove_stopwords)
data['text_tokens'] = data['text_tokens'].apply(remove_stopwords)
data.head()

,title,text,label,title_tokens,text_tokens
Unnamed: 0,,,,,
0,law enforcement on high alert following threat...,no comment is expected from barack obama membe...,1,law enforcement high alert following threats ...,comment expected barack obama members fyf...
2,unbelievable obama s attorney general says mo...,now most of the demonstrators gathered last ...,1,unbelievable obama attorney general says cha...,demonstrators gathered last night exercis...
3,bobby jindal raised hindu uses story of chri...,a dozen politically active pastors came here f...,0,bobby jindal raised hindu uses story christia...,dozen politically active pastors came priv...
4,satan 2 russia unvelis an image of its terrif...,the rs 28 sarmat missile dubbed satan 2 will...,1,satan 2 russia unvelis image terrifying new...,rs 28 sarmat missile dubbed satan 2 replace ...
5,about time christian group sues amazon and sp...,all we can say on this one is it s about time ...,1,time christian group sues amazon splc desig...,say one time someone sued southern p...

## Stemming

In [21]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [22]:
data['title_tokens'] = data['title_tokens'].apply(stem_words)
data['text_tokens'] = data['text_tokens'].apply(stem_words)
data

,title,text,label,title_tokens,text_tokens
Unnamed: 0,,,,,
0,law enforcement on high alert following threat...,no comment is expected from barack obama membe...,1,law enforc high alert follow threat cop white ...,comment expect barack obama member fyf911 fuky...
2,unbelievable obama s attorney general says mo...,now most of the demonstrators gathered last ...,1,unbeliev obama attorney gener say charlott rio...,demonstr gather last night exercis constitut p...
3,bobby jindal raised hindu uses story of chri...,a dozen politically active pastors came here f...,0,bobbi jindal rais hindu use stori christian co...,dozen polit activ pastor came privat dinner fr...
4,satan 2 russia unvelis an image of its terrif...,the rs 28 sarmat missile dubbed satan 2 will...,1,satan 2 russia unv imag terrifi new supernuk w...,rs 28 sarmat missil dub satan 2 replac ss 18 f...
5,about time christian group sues amazon and sp...,all we can say on this one is it s about time ...,1,time christian group sue amazon splc design ha...,say one time someon su southern poverti law ce...
...,...,...,...,...,...
72129,russians steal research on trump in hack of u ...,washington reuters hackers believed to be ...,0,russian steal research trump hack u democrat p...,washington reuter hacker believ work russian g...
72130,watch giuliani demands that democrats apolog...,you know because in fantasyland republicans n...,1,watch giuliani demand democrat apolog trump ra...,know fantasyland republican never question cit...
72131,migrants refuse to leave train at refugee camp...,migrants refuse to leave train at refugee camp...,0,migrant refus leav train refuge camp hungari,migrant refus leav train refuge camp hungari t...
72132,trump tussle gives unpopular mexican leader mu...,mexico city reuters donald trump s combati...,0,trump tussl give unpopular mexican leader much...,mexico citi reuter donald trump comb style buf...
72133,goldman sachs endorses hillary clinton for pre...,goldman sachs endorses hillary clinton for pre...,1,goldman sach endors hillari clinton presid,goldman sach endors hillari clinton presid gol...

In [23]:
y = data['label']
y

Unnamed: 0
0        1
2        1
3        0
4        1
5        1
        ..
72129    0
72130    1
72131    0
72132    0
72133    1
Name: label, Length: 71537, dtype: int64

## Separate preprocessed data

In [24]:
data['clean_text'] = data['title_tokens'] + " " + data['text_tokens']
data

,title,text,label,title_tokens,text_tokens,clean_text
Unnamed: 0,,,,,,
0,law enforcement on high alert following threat...,no comment is expected from barack obama membe...,1,law enforc high alert follow threat cop white ...,comment expect barack obama member fyf911 fuky...,law enforc high alert follow threat cop white ...
2,unbelievable obama s attorney general says mo...,now most of the demonstrators gathered last ...,1,unbeliev obama attorney gener say charlott rio...,demonstr gather last night exercis constitut p...,unbeliev obama attorney gener say charlott rio...
3,bobby jindal raised hindu uses story of chri...,a dozen politically active pastors came here f...,0,bobbi jindal rais hindu use stori christian co...,dozen polit activ pastor came privat dinner fr...,bobbi jindal rais hindu use stori christian co...
4,satan 2 russia unvelis an image of its terrif...,the rs 28 sarmat missile dubbed satan 2 will...,1,satan 2 russia unv imag terrifi new supernuk w...,rs 28 sarmat missil dub satan 2 replac ss 18 f...,satan 2 russia unv imag terrifi new supernuk w...
5,about time christian group sues amazon and sp...,all we can say on this one is it s about time ...,1,time christian group sue amazon splc design ha...,say one time someon su southern poverti law ce...,time christian group sue amazon splc design ha...
...,...,...,...,...,...,...
72129,russians steal research on trump in hack of u ...,washington reuters hackers believed to be ...,0,russian steal research trump hack u democrat p...,washington reuter hacker believ work russian g...,russian steal research trump hack u democrat p...
72130,watch giuliani demands that democrats apolog...,you know because in fantasyland republicans n...,1,watch giuliani demand democrat apolog trump ra...,know fantasyland republican never question cit...,watch giuliani demand democrat apolog trump ra...
72131,migrants refuse to leave train at refugee camp...,migrants refuse to leave train at refugee camp...,0,migrant refus leav train refuge camp hungari,migrant refus leav train refuge camp hungari t...,migrant refus leav train refuge camp hungari m...
72132,trump tussle gives unpopular mexican leader mu...,mexico city reuters donald trump s combati...,0,trump tussl give unpopular mexican leader much...,mexico citi reuter donald trump comb style buf...,trump tussl give unpopular mexican leader much...
72133,goldman sachs endorses hillary clinton for pre...,goldman sachs endorses hillary clinton for pre...,1,goldman sach endors hillari clinton presid,goldman sach endors hillari clinton presid gol...,goldman sach endors hillari clinton presid gol...

## Train Test Split

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(data['clean_text'],y, test_size = 0.3, random_state=23)

## Vectorize data using various vectorizers

In [27]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
cv = CountVectorizer()
cvb = CountVectorizer(ngram_range=(2,2)) # bigram
cvt = CountVectorizer(max_features=50000, ngram_range=(3,3)) # trigram
tfidf = TfidfVectorizer()

In [28]:
cv_encoded_train= cv.fit_transform(X_train)
cvb_encoded_train= cvb.fit_transform(X_train)
cvt_encoded_train= cvt.fit_transform(X_train)
tfidf_encoded_train= tfidf.fit_transform(X_train)

In [29]:
print(len(cv.vocabulary_))
print(len(cvb.vocabulary_))
print(len(cvt.vocabulary_))
print(len(tfidf.vocabulary_))

163834
4982127
50000
163834

In [30]:
cv_encoded_test= cv.transform(X_test)
cvb_encoded_test= cvb.transform(X_test)
cvt_encoded_test= cvt.transform(X_test)
tfidf_encoded_test= tfidf.transform(X_test)

## Train Logistic model

In [31]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression(max_iter=5000)
model2 = LogisticRegression(max_iter=5000)
model3 = LogisticRegression(max_iter=5000)
model4 = LogisticRegression(max_iter=5000)
model1.fit(cv_encoded_train, y_train)
model2.fit(cvb_encoded_train, y_train)
model3.fit(cvt_encoded_train, y_train)
model4.fit(tfidf_encoded_train, y_train)

LogisticRegression(max_iter=5000)

In [32]:
print(model1.score(cv_encoded_test, y_test))
print(model2.score(cvb_encoded_test, y_test))
print(model3.score(cvt_encoded_test, y_test))
print(model4.score(tfidf_encoded_test, y_test))

0.9564812226260367
0.9590904855092722
0.9402665175659305
0.9488864038766192

In [33]:
y_pred_cv=model1.predict(cv_encoded_test)
y_pred_cvb=model2.predict(cvb_encoded_test)
y_pred_cvt=model3.predict(cvt_encoded_test)
y_pred_tfidf=model4.predict(tfidf_encoded_test)

### The Logistic regression model yielded the best result when the input data was vectorized using bag of bi-grams.

## Train Naive Bayes' Model

In [34]:
from sklearn.naive_bayes import MultinomialNB
nb1 = MultinomialNB()
nb2 = MultinomialNB()
nb3 = MultinomialNB()
nb4 = MultinomialNB()
nb1

MultinomialNB()

In [35]:
nb1.fit(cv_encoded_train, y_train)
nb2.fit(cvb_encoded_train, y_train)
nb3.fit(cvt_encoded_train, y_train)
nb4.fit(tfidf_encoded_train, y_train)

MultinomialNB()

In [36]:
print(nb1.score(cv_encoded_test, y_test))
print(nb2.score(cvb_encoded_test, y_test))
print(nb3.score(cvt_encoded_test, y_test))
print(nb4.score(tfidf_encoded_test, y_test))

0.8943714472090206
0.9385425403037928
0.9174354673376199
0.8695368558382257

In [37]:
y1_pred_cv=nb1.predict(cv_encoded_test)
y1_pred_cvb=nb2.predict(cvb_encoded_test)
y1_pred_cvt=nb3.predict(cvt_encoded_test)
y1_pred_tfidf=nb4.predict(tfidf_encoded_test)

### The Multinomial NB model yielded the best result when the input data was vectorized using bag of bi-grams.

## Get classification report

In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_pred_cvb, y_test))
print(classification_report(y1_pred_cvb, y_test))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96     10251
           1       0.97      0.95      0.96     11211

    accuracy                           0.96     21462
   macro avg       0.96      0.96      0.96     21462
weighted avg       0.96      0.96      0.96     21462

              precision    recall  f1-score   support

           0       0.96      0.92      0.94     10908
           1       0.92      0.96      0.94     10554

    accuracy                           0.94     21462
   macro avg       0.94      0.94      0.94     21462
weighted avg       0.94      0.94      0.94     21462

###

## make a pipeline using vectorizer and model with the highest scores(bi-grams and Logistic Regression model)

In [39]:
from sklearn.pipeline import Pipeline
pipe = Pipeline([('vectorizer', CountVectorizer(max_features=70000, ngram_range=(2,2))),
    ('model', LogisticRegression(max_iter=5000))])
pipe

Pipeline(steps=[('vectorizer',
                 CountVectorizer(max_features=70000, ngram_range=(2, 2))),
                ('model', LogisticRegression(max_iter=5000))])

In [40]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('vectorizer',
                 CountVectorizer(max_features=70000, ngram_range=(2, 2))),
                ('model', LogisticRegression(max_iter=5000))])

In [41]:
pipe.score(X_test,y_test)

0.9613269965520455

In [42]:
from joblib import dump
dump(pipe, '../fake_news_model.joblib')

['../fake_news_model.joblib']